allowinworlds:
  - survival
  - survival_end
  - survival_nether
#In what worlds should players be allowed to set their homes?

pvpdefault: true
#Should people be allowed to hit each other by default?
pvprunsin:
  - survival
  - survival_end
  - survival_nether

censor-invisibility: true
#Should invisible players have their names censored